In [94]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

In [95]:
df = pd.read_excel('train_data.xlsx')
df.head()

,property_id,location_id,RowID,no_of_bathrooms,degree_of_latitude,degree_of_longitude,no_of_bedrooms,space_occupied,listing_purpose,category_property,listing_date,estate_agency,salesperson,area,has_garage,price
0,13845428,3847,30000,7.0,31.526751,74.337072,7.0,1 Kanal,For Rent,Houseo,2019-02-24,Raja Real Estate,Raja Adeeb,"Gulberg, Lahore, Punjab",False,300000
1,13851899,1487,30001,6.0,31.502385,74.414506,6.0,10 Marla,For Rent,House,2019-07-24,Dream Developers & Property Consultants,Ali Auwn,"Divine Gardens, Lahore, Punjab",False,90000
2,13852192,1447,30002,NaN,31.462493,74.409342,NaN,4 Marla,For Rent,Room,2018-12-26,Property Channel,Abbas Ali,"DHA Defence, Lahore, Punjab",True,15000
3,13855250,1006,30003,3.0,31.432105,74.349117,2.0,4 Marla,For Rent,Lower Portion,2019-06-24,Syed Associates & Builders,Syed Talha,"Pak Arab Housing Society, Lahore, Punjab",False,21000
4,13855556,1006,30004,6.0,31.432105,74.349117,4.0,5 Marla,For Rent,House,2019-07-18,Syed Associates & Builders,Syed Talha,"Pak Arab Housing Society, Lahore, Punjab",True,43000

In [96]:
df.to_csv("train_data.csv", index=False)

In [97]:
df = pd.read_csv('train_data.csv')

df.head()

,property_id,location_id,RowID,no_of_bathrooms,degree_of_latitude,degree_of_longitude,no_of_bedrooms,space_occupied,listing_purpose,category_property,listing_date,estate_agency,salesperson,area,has_garage,price
0,13845428,3847,30000,7.0,31.526751,74.337072,7.0,1 Kanal,For Rent,Houseo,2019-02-24,Raja Real Estate,Raja Adeeb,"Gulberg, Lahore, Punjab",False,300000
1,13851899,1487,30001,6.0,31.502385,74.414506,6.0,10 Marla,For Rent,House,2019-07-24,Dream Developers & Property Consultants,Ali Auwn,"Divine Gardens, Lahore, Punjab",False,90000
2,13852192,1447,30002,NaN,31.462493,74.409342,NaN,4 Marla,For Rent,Room,2018-12-26,Property Channel,Abbas Ali,"DHA Defence, Lahore, Punjab",True,15000
3,13855250,1006,30003,3.0,31.432105,74.349117,2.0,4 Marla,For Rent,Lower Portion,2019-06-24,Syed Associates & Builders,Syed Talha,"Pak Arab Housing Society, Lahore, Punjab",False,21000
4,13855556,1006,30004,6.0,31.432105,74.349117,4.0,5 Marla,For Rent,House,2019-07-18,Syed Associates & Builders,Syed Talha,"Pak Arab Housing Society, Lahore, Punjab",True,43000

In [98]:
df['salesperson'].value_counts()

salesperson
Azam Ali                                                                       797
Boez Ayub                                                                      787
Muhammad Imran                                                                 594
Kashif                                                                         397
Daud Ahmad(Co-CEO), Shafique Arshad Waince(Co-CEO), Zafar Iqbal Bajwa (CEO)    375
                                                                              ...
Moazzam Nawaz                                                                    1
Cptn Zeeshan                                                                     1
Syed Nasir                                                                       1
Khawaja M. Arshad                                                                1
TALHA   MIAN AHMAD                                                               1
Name: count, Length: 10647, dtype: int64

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 161393 entries, 0 to 161392
Data columns (total 16 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   property_id          161393 non-null  int64
 1   location_id          161393 non-null  int64
 2   RowID                161393 non-null  int64
 3   no_of_bathrooms      129205 non-null  float64
 4   degree_of_latitude   161393 non-null  float64
 5   degree_of_longitude  161393 non-null  float64
 6   no_of_bedrooms       145317 non-null  float64
 7   space_occupied       161393 non-null  object
 8   listing_purpose      161393 non-null  object
 9   category_property    161393 non-null  object
 10  listing_date         161393 non-null  object
 11  estate_agency        134700 non-null  object
 12  salesperson          134699 non-null  object
 13  area                 161393 non-null  object
 14  has_garage           161393 non-null  bool
 15  price                161393 non-null  int64
dtypes: bool(1), float64(4), int64(4), object(7)
memory usage: 18.6+ MB

In [100]:

# Check for missing data
missing_values = df.isnull().sum()
print(missing_values)

property_id                0
location_id                0
RowID                      0
no_of_bathrooms        32188
degree_of_latitude         0
degree_of_longitude        0
no_of_bedrooms         16076
space_occupied             0
listing_purpose            0
category_property          0
listing_date               0
estate_agency          26693
salesperson            26694
area                       0
has_garage                 0
price                      0
dtype: int64

In [101]:
df.shape

(161393, 16)

In [102]:
df.isnull().sum()/len(df)*100

property_id             0.000000
location_id             0.000000
RowID                   0.000000
no_of_bathrooms        19.943864
degree_of_latitude      0.000000
degree_of_longitude     0.000000
no_of_bedrooms          9.960779
space_occupied          0.000000
listing_purpose         0.000000
category_property       0.000000
listing_date            0.000000
estate_agency          16.539131
salesperson            16.539751
area                    0.000000
has_garage              0.000000
price                   0.000000
dtype: float64

In [103]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, StandardScaler, MinMaxScaler
# from sklearn.impute import SimpleImputer, KNNImputer
# from sklearn.feature_selection import VarianceThreshold

# # Define the column transformer with multiple preprocessing options
# transformer = ColumnTransformer(
#     transformers=[
#         # Ordinal encoding for ordered categorical features
#         ('ordinal',
#          OrdinalEncoder(categories=[[]]),
#          []),  # Replace with your actual ordered categorical columns

#         # Label encoding for non-ordered categorical features
#         # (applied as a pipeline step, using OrdinalEncoder here as a substitute for LabelEncoder)
#         ('label',
#          OrdinalEncoder(),
#          ['']),  # Replace 'NonOrderedColumn' with your actual column names for label encoding

#         # One-hot encoding for nominal categorical features
#         ('onehot',
#          OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore'),
#          ['listing_purpose','has_garage']),  # Replace with your nominal categorical columns

#         # Imputation for missing values in numerical columns (SimpleImputer)
#         ('imputer_num_simple',
#          SimpleImputer(strategy='mean'),
#          []),  # Replace with your numerical columns for simple imputation

#         # Imputation for missing values in numerical columns (KNNImputer)
#         ('imputer_num_knn',
#          KNNImputer(n_neighbors=5),
#          ['no_of_bathrooms','no_of_bedrooms']),  # Replace with your numerical columns for KNN imputation

#         # Imputation for missing values in categorical columns
#         ('imputer_cat',
#          SimpleImputer(strategy='most_frequent'),
#          ['estate_agency','salesperson']),  # Replace with your categorical columns

#         # Standard scaling for numerical columns
#         ('scaler',
#          StandardScaler(),
#          []),  # Replace with your numerical columns for standard scaling

#         # Min-max scaling for numerical columns
#         ('minmax_scaler',
#          MinMaxScaler(),
#          []),  # Replace with your numerical columns for min-max scaling

#         # Variance threshold for feature selection
#         ('variance_threshold',
#          VarianceThreshold(threshold=0.01),
#          []),  # Replace with your columns for variance thresholding
#     ],
#     # Default action for columns not explicitly mentioned
#     remainder='passthrough'  # Keeps the columns not specified as-is
# )

# # Apply the column transformer to training and testing data
# X_train_transformed = transformer.fit_transform(X_train)
# X_test_transformed = transformer.transform(X_test)

In [104]:
df.duplicated().sum()

0

In [105]:
# Ensure the space_occupied column is a string type
df['space_occupied'] = df['space_occupied'].astype(str)

# Split the column into two parts: number and unit
split_data = df['space_occupied'].str.split(' ', expand=True)

# Replace commas with empty strings before converting to float
df['quantity'] = split_data[0].str.replace(',', '').astype(float)  # Convert the number part to float

df['unit'] = split_data[1]  # Extract the unit

# Convert Kanal to Marla
df.loc[df['unit'] == 'Kanal', 'quantity'] *= 20
df.loc[df['unit'] == 'Kanal', 'unit'] = 'Marla'

# Rejoin the quantity and unit into the space_occupied column
df['space_occupied'] = df['quantity'].astype(int).astype(str)

# Drop intermediate columns if no longer needed
df.drop(columns=['quantity', 'unit'], inplace=True)

df.sample(20)

,property_id,location_id,RowID,no_of_bathrooms,degree_of_latitude,degree_of_longitude,no_of_bedrooms,space_occupied,listing_purpose,category_property,listing_date,estate_agency,salesperson,area,has_garage,price
61240,16687804,156,91240,6.0,33.737402,73.179159,6.0,5,For Sale,House,2019-06-13,Islamabad Real Estate,Kamran abbasi,"Bhara kahu, Islamabad, Islamabad Capital",True,6000000
29507,15669459,232,59507,NaN,24.926606,67.130384,3.0,4,For Sale,Flat,2019-06-21,Sydney Estate & Marketing,Sydney Estate Marketing,"Gulistan-e-Jauhar, Karachi, Sindh",True,9000000
131599,17278615,11761,161599,3.0,25.051778,67.319934,3.0,5,For Sale,Flat,2019-07-14,ZPN Real Estate & Builders,Muhammad Asif,"Bahria Town Karachi, Karachi, Sindh",True,6000000
156542,17427936,168,186542,1.0,33.669533,73.000073,3.0,3,For Sale,Flat,2019-07-22,A S International,Ch ijaz Ahmad,"G-11, Islamabad, Islamabad Capital",False,5000000
17141,15091198,11905,47141,5.0,33.538087,73.164536,4.0,11,For Sale,Flat,2019-03-06,NaN,NaN,"DHA Defence, Islamabad, Islamabad Capital",False,19000000
44890,16243677,1592,74890,NaN,31.466410,74.383621,7.0,20,For Sale,Houseo,2019-06-25,Maan Estate,Zain and Mateen,"DHA Defence, Lahore, Punjab",True,67500000
112899,17150540,8298,142899,5.0,24.894076,67.027715,4.0,5,For Sale,Housev,2019-07-04,Sydney Estate & Marketing,Sydney Estate Marketing,"Bahria Town Karachi, Karachi, Sindh",False,13000000
119930,17201545,329,149930,1.0,33.698137,72.978215,1.0,8,For Rent,Flat,2019-07-11,Noman Enterprises,M. Noman,"E-11, Islamabad, Islamabad Capital",True,30000
129688,17264523,6853,159688,8.0,24.964623,67.168558,8.0,9,For Sale,House,2019-07-14,Al Affan Real Estate,Syed Aqeel Shaikh,"Scheme 33, Karachi, Sindh",False,25700000
73648,16860244,12199,103648,NaN,33.566646,73.116842,2.0,3,For Rent,Flatx,2019-06-21,Pak Property Real Estate,Asif idress,"Bahria Town Rawalpindi, Rawalpindi, Punjab",False,32000
61368,16692743,739,91368,2.0,33.569040,73.095295,2.0,3,For Sale,House,2019-06-13,NaN,NaN,"Gulistan Colony, Rawalpindi, Punjab",True,2800000
101375,17072654,3444,131375,5.0,33.662782,73.077793,4.0,12,For Rent,Lower Portion,2019-07-03,Property Way,Shahid KhanUmair Hashmi,"I-8, Islamabad, Islamabad Capital",True,75000
78544,16924881,1369,108544,9.0,31.566287,74.298735,9.0,16,For Sale,House,2019-06-27,Al Khaiber Estate and Builder,Mian Khurram,"Islampura, Lahore, Punjab",False,27000000
53858,16510504,1504,83858,5.0,33.543004,73.067576,4.0,10,For Sale,Housec,2019-06-27,Estate Investment,Major R Sultan Sikandar,"Askari 14, Rawalpindi, Punjab",True,18000000
86773,16990468,3733,116773,NaN,31.441113,74.239683,4.0,5,For Sale,House,2019-06-29,NaN,NaN,"Eden, Lahore, Punjab",False,10500000
145605,17338870,632,175605,1.0,33.550623,73.123112,6.0,12,For Sale,House,2019-07-17,Hassan Associate,Rana Nadeem Sarwar,"Bahria Town Rawalpindi, Rawalpindi, Punjab",True,22500000
131191,17271190,3067,161191,1.0,33.489836,73.101611,NaN,7,For Rent,House,2019-07-13,Eiffel Estate,Umar Jamil,"Bahria Town Rawalpindi, Rawalpindi, Punjab",False,25000
146551,17342264,7078,176551,1.0,24.906134,67.023983,1.0,8,For Sale,House,2019-07-17,Al Habib Estate,Mohsin Habib,"Nazimabad, Karachi, Sindh",True,32500000
98822,17064436,377,128822,1.0,31.539206,74.305515,4.0,3,For Sale,House,2019-07-02,Syed Estate Agency,Syed Ali Abbas,"Samanabad, Lahore, Punjab",True,7000000
113656,17159585,373,143656,7.0,31.405370,74.257078,7.0,20,For Sale,Lower Portion,2019-07-10,Burhan Estate And Advisor,"Muhammad Ashraf Khan, Sheraz Gul Khan","Valencia Housing Society, Lahore, Punjab",True,18000000

In [106]:
df['listing_date'] = pd.to_datetime(df['listing_date'])

# Extract year, month, and day into separate columns
df['listing_year'] = df['listing_date'].dt.year
df['listing_month'] = df['listing_date'].dt.month
df['listing_day'] = df['listing_date'].dt.day

df.head()

,property_id,location_id,RowID,no_of_bathrooms,degree_of_latitude,degree_of_longitude,no_of_bedrooms,space_occupied,listing_purpose,category_property,listing_date,estate_agency,salesperson,area,has_garage,price,listing_year,listing_month,listing_day
0,13845428,3847,30000,7.0,31.526751,74.337072,7.0,20,For Rent,Houseo,2019-02-24,Raja Real Estate,Raja Adeeb,"Gulberg, Lahore, Punjab",False,300000,2019,2,24
1,13851899,1487,30001,6.0,31.502385,74.414506,6.0,10,For Rent,House,2019-07-24,Dream Developers & Property Consultants,Ali Auwn,"Divine Gardens, Lahore, Punjab",False,90000,2019,7,24
2,13852192,1447,30002,NaN,31.462493,74.409342,NaN,4,For Rent,Room,2018-12-26,Property Channel,Abbas Ali,"DHA Defence, Lahore, Punjab",True,15000,2018,12,26
3,13855250,1006,30003,3.0,31.432105,74.349117,2.0,4,For Rent,Lower Portion,2019-06-24,Syed Associates & Builders,Syed Talha,"Pak Arab Housing Society, Lahore, Punjab",False,21000,2019,6,24
4,13855556,1006,30004,6.0,31.432105,74.349117,4.0,5,For Rent,House,2019-07-18,Syed Associates & Builders,Syed Talha,"Pak Arab Housing Society, Lahore, Punjab",True,43000,2019,7,18

In [107]:
df = df.drop('property_id', axis=1)
df = df.drop('listing_date', axis=1)
df = df.drop('RowID', axis=1)
df.head()

,location_id,no_of_bathrooms,degree_of_latitude,degree_of_longitude,no_of_bedrooms,space_occupied,listing_purpose,category_property,estate_agency,salesperson,area,has_garage,price,listing_year,listing_month,listing_day
0,3847,7.0,31.526751,74.337072,7.0,20,For Rent,Houseo,Raja Real Estate,Raja Adeeb,"Gulberg, Lahore, Punjab",False,300000,2019,2,24
1,1487,6.0,31.502385,74.414506,6.0,10,For Rent,House,Dream Developers & Property Consultants,Ali Auwn,"Divine Gardens, Lahore, Punjab",False,90000,2019,7,24
2,1447,NaN,31.462493,74.409342,NaN,4,For Rent,Room,Property Channel,Abbas Ali,"DHA Defence, Lahore, Punjab",True,15000,2018,12,26
3,1006,3.0,31.432105,74.349117,2.0,4,For Rent,Lower Portion,Syed Associates & Builders,Syed Talha,"Pak Arab Housing Society, Lahore, Punjab",False,21000,2019,6,24
4,1006,6.0,31.432105,74.349117,4.0,5,For Rent,House,Syed Associates & Builders,Syed Talha,"Pak Arab Housing Society, Lahore, Punjab",True,43000,2019,7,18

In [108]:
# Ensure the space_occupied column is a string type
df['area'] = df['area'].astype(str)

# Split the column into two parts: number and unit
split_data = df['area'].str.split(',', expand=True)

df['town'] = split_data[0]

df['city'] = split_data[1]  # Extract the unit
df['province'] = split_data[2]  # Extract the unit



df.drop(columns=['area'], inplace=True)

df.sample(20)

,location_id,no_of_bathrooms,degree_of_latitude,degree_of_longitude,no_of_bedrooms,space_occupied,listing_purpose,category_property,estate_agency,salesperson,has_garage,price,listing_year,listing_month,listing_day,town,city,province
49799,7216,1.0,24.935635,67.051020,1.0,7,For Sale,Flat,Al-Rehman Estate,Al-Rehman Estate,False,14500000,2019,6,5,North Nazimabad,Karachi,Sindh
142030,3053,1.0,33.489746,73.079553,1.0,10,For Sale,House,Sargodha Real Estate & Builders,Faisal,False,16000000,2019,7,16,Bahria Town Rawalpindi,Rawalpindi,Punjab
83373,6937,3.0,24.877239,67.033526,3.0,2,For Sale,Flat,NaN,NaN,False,3500000,2019,6,28,Jamshed Town,Karachi,Sindh
16230,6008,NaN,33.653209,73.089802,3.0,4,For Sale,House,Danial Property Adviser,Raees Satti,True,15000000,2019,3,6,Dhok Kala Khan,Rawalpindi,Punjab
47472,534,1.0,31.378610,73.129245,1.0,8,For Rent,Lower Portion,Al Qasim Estate Agency,"Daud Ahmad(Co-CEO), Shafique Arshad Waince(Co-...",False,25000,2019,5,18,Satiana Road,Faisalabad,Punjab
52729,9030,3.0,25.020961,67.321172,3.0,4,For Sale,Flath,Land Professional Associate,Rao Irfan,False,6300000,2019,6,27,Bahria Town Karachi,Karachi,Sindh
36633,4256,NaN,31.463957,74.309950,3.0,5,For Rent,Lower Portion,The Nine 110 Property Advisor,M. Fakhar Abbas,False,25000,2019,4,25,Township,Lahore,Punjab
156452,1442,NaN,31.483283,74.395723,7.0,20,For Sale,House,Lahore Grande Estate,Hafiz Murtaza,False,41000000,2019,7,22,DHA Defence,Lahore,Punjab
62207,8296,5.0,31.425441,73.145077,4.0,5,For Sale,House,Makkah Estate,Muhammad Asif,False,9500000,2019,6,25,Eden Gardens,Faisalabad,Punjab
95416,4190,1.0,31.446824,74.404736,7.0,20,For Sale,House,Al Burraq Properties,Jawad Ahmad,True,35000000,2019,7,1,State Life Housing Society,Lahore,Punjab
25565,3987,1.0,31.409436,74.188914,4.0,3,For Sale,House,NaN,NaN,True,6600000,2019,6,27,Jubilee Town,Lahore,Punjab
71759,340,6.0,33.713488,73.162680,6.0,5,For Rent,House,Madina Property Advisor,Fareed Abbassi Abdu,False,35000,2019,6,27,Bani Gala,Islamabad,Islamabad Capital
91221,330,1.0,33.650065,72.963681,1.0,4,For Rent,Lower Portion,Asset Planner,Faheem Khan,True,26000,2019,6,30,G-13,Islamabad,Islamabad Capital
25056,9155,1.0,33.584261,73.121663,1.0,5,For Sale,House,Ashraf Real Estate,Hafeez Ud Din,False,7000000,2019,5,5,Airport Housing Society,Rawalpindi,Punjab
39058,3952,8.0,31.470144,74.296281,7.0,24,For Sale,House,Rose Five Star International Real Estate,Malik Shahnawaz Hanya,True,44900000,2019,6,28,Johar Town,Lahore,Punjab
63690,1474,6.0,31.317861,74.218140,6.0,20,For Sale,House,Athar Associates & Real Estate (Bahria Orchard),Zeeshan,False,18500000,2019,6,18,Bahria Orchard,Lahore,Punjab
798,6691,3.0,24.926606,67.067707,3.0,4,For Sale,Flat,Zainab Associates,Muhammad Ashfaq,False,5800000,2019,6,14,Federal B Area,Karachi,Sindh
51618,6837,5.0,24.912026,67.130733,4.0,6,For Sale,Flatk,Makkah Associates,Bilal,True,11000000,2019,6,5,Gulistan-e-Jauhar,Karachi,Sindh
91267,165,NaN,33.720413,73.056493,9.0,20,For Rent,House,ApniChat. Com,Zawar Nazir,True,450000,2019,6,30,F-7,Islamabad,Islamabad Capital
74851,9031,5.0,25.009119,67.307179,4.0,6,For Sale,House,Legend Developers,Uneeb Sheikh,False,14500000,2019,6,28,Bahria Town Karachi,Karachi,Sindh

In [109]:
value_counts_df = df['category_property'].value_counts().reset_index()
value_counts_df.columns = ['Value', 'Count']

with pd.option_context('display.max_rows', None):
    print(value_counts_df)

              Value  Count
0             House  89821
1              Flat  29820
2     Upper Portion  14700
3     Lower Portion   9380
4              Room    704
5        Farm House    527
6            Housea    416
7            Housef    414
8            Houses    414
9            Houseg    411
10           Housei    408
11           Housem    408
12           Housex    404
13           Houseu    402
14           Houseo    400
15           Housee    398
16           Houset    397
17           Housec    397
18           Housez    392
19           Housek    390
20           Househ    387
21           Houseq    386
22           Housed    385
23           Housey    380
24           Housep    380
25           Housew    375
26           Housev    369
27           Houser    366
28           Houseb    364
29           Housen    363
30           Housel    361
31           Housej    343
32        Penthouse    262
33            Flatw    148
34            Flatj    143
35            Flatf    142
36            Flate    142
37            Flatb    140
38            Flatv    140
39            Flatk    137
40            Flatg    132
41            Flatd    131
42            Flatn    130
43            Flatp    130
44            Flatc    130
45            Flatx    128
46            Flatz    126
47            Flatl    125
48            Flats    124
49            Flatm    122
50            Flati    119
51            Flaty    119
52            Flatr    118
53            Flatu    118
54            Flath    117
55            Flatt    117
56            Flata    113
57            Flato    111
58            Flatq    111
59   Upper Portiony     76
60   Upper Portionh     70
61   Upper Portioni     69
62   Upper Portionp     67
63   Upper Portionu     66
64   Upper Portionq     66
65   Upper Portione     65
66   Upper Portiont     65
67   Upper Portionv     65
68   Upper Portionb     64
69   Upper Portionj     64
70   Upper Portionn     64
71   Upper Portionx     63
72   Upper Portiona     60
73   Upper Portionr     60
74   Upper Portiong     59
75   Upper Portionl     58
76   Upper Portiono     58
77   Upper Portiond     58
78   Upper Portionw     57
79   Upper Portionc     57
80   Upper Portions     56
81   Upper Portionz     56
82   Upper Portionf     54
83   Upper Portionm     52
84   Upper Portionk     50
85   Lower Portionp     47
86   Lower Portionf     46
87   Lower Portions     46
88   Lower Portionk     46
89   Lower Portionm     45
90   Lower Portiond     44
91   Lower Portiony     42
92   Lower Portionq     42
93   Lower Portiong     41
94   Lower Portionj     41
95   Lower Portionc     41
96   Lower Portionb     40
97   Lower Portione     40
98   Lower Portionz     40
99   Lower Portionv     39
100  Lower Portionx     38
101  Lower Portioni     38
102  Lower Portiono     35
103  Lower Portionw     35
104  Lower Portionh     33
105  Lower Portionn     31
106  Lower Portiona     30
107  Lower Portionu     30
108  Lower Portionl     30
109  Lower Portiont     28
110  Lower Portionr     26
111           Roomg      8
112           Roomx      7
113           Roomf      7
114           Roomj      6
115     Farm Housek      5
116           Rooms      5
117           Roomq      5
118           Rooml      5
119           Roomy      4
120     Farm Housen      4
121      Penthouser      4
122           Roomw      4
123           Roomi      4
124           Roomm      4
125           Roomn      4
126     Farm Housel      4
127      Penthousep      4
128     Farm Housep      4
129     Farm Housef      3
130           Roomz      3
131      Penthousey      3
132           Roomo      3
133           Roomp      3
134     Farm Houseb      3
135           Roomu      3
136           Roomd      3
137           Roomr      3
138      Penthousen      3
139           Roomc      3
140           Roomv      3
141           Roomk      3
142     Farm Househ      2
143     Farm Housej      2
144     Farm Housey      2
145           Roomb      2
146           Rooma      2
147     Farm Houseo      2
148     Farm Housev      2
149     Farm Houseu      2
150      Penthouseu      2
151     Farm Housea      2
152      Penthouset      2
153      Penthouseq      1
154     Farm Houset      1
155     Farm Housez      1
156      Penthouseb      1
157           Roome      1
158           Roomh      1
159      Penthousec      1
160     Farm Houseq      1
161     Farm Housex      1
162      Penthousei      1
163     Farm Houser      1
164     Farm Houseg      1
165      Penthouseg      1
166     Farm Housed      1

In [110]:
!pip install fuzzywuzzy

Requirement already satisfied: fuzzywuzzy in /usr/local/lib/python3.10/dist-packages (0.18.0)

In [111]:
from fuzzywuzzy import process

# Define correct categories
correct_values = ['House', 'Flat', 'Upper Portion', 'Lower Portion', 'Room', 'Farm House']

# Function to map similar values
def correct_value(val):
    match, score = process.extractOne(val, correct_values)
    return match if score > 80 else val  # Adjust threshold as needed

df['category_property'] = df['category_property'].apply(correct_value)

In [112]:
# correct_values = ['House', 'Flat', 'Upper Portion', 'Lower Portion', 'Room', 'Farm House']


# if df['category_property'].len() == correct_values[i].len()+1

df['category_property'].value_counts()

category_property
House            100216
Flat              33133
Upper Portion     16299
Lower Portion     10374
Room                800
Farm House          571
Name: count, dtype: int64

In [113]:
df.head()

,location_id,no_of_bathrooms,degree_of_latitude,degree_of_longitude,no_of_bedrooms,space_occupied,listing_purpose,category_property,estate_agency,salesperson,has_garage,price,listing_year,listing_month,listing_day,town,city,province
0,3847,7.0,31.526751,74.337072,7.0,20,For Rent,House,Raja Real Estate,Raja Adeeb,False,300000,2019,2,24,Gulberg,Lahore,Punjab
1,1487,6.0,31.502385,74.414506,6.0,10,For Rent,House,Dream Developers & Property Consultants,Ali Auwn,False,90000,2019,7,24,Divine Gardens,Lahore,Punjab
2,1447,NaN,31.462493,74.409342,NaN,4,For Rent,Room,Property Channel,Abbas Ali,True,15000,2018,12,26,DHA Defence,Lahore,Punjab
3,1006,3.0,31.432105,74.349117,2.0,4,For Rent,Lower Portion,Syed Associates & Builders,Syed Talha,False,21000,2019,6,24,Pak Arab Housing Society,Lahore,Punjab
4,1006,6.0,31.432105,74.349117,4.0,5,For Rent,House,Syed Associates & Builders,Syed Talha,True,43000,2019,7,18,Pak Arab Housing Society,Lahore,Punjab

In [115]:
X = df.drop('price', axis=1)
y = df['price']

# Splitting into train and test sets (80/20 split)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [116]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer, KNNImputer

# Define the column transformer with multiple preprocessing options
transformer = ColumnTransformer(
    transformers=[

        # Imputation for missing values in numerical columns (KNNImputer)
        ('imputer_num_knn',
         KNNImputer(n_neighbors=5),
         ['no_of_bathrooms','no_of_bedrooms']),  # Replace with your numerical columns for KNN imputation

        # Imputation for missing values in categorical columns
        ('imputer_cat',
         SimpleImputer(strategy='most_frequent'),
         ['estate_agency','salesperson']),  # Replace with your categorical columns

    ],
    # Default action for columns not explicitly mentioned
    remainder='passthrough'  # Keeps the columns not specified as-is
)

# Apply the column transformer to training and testing data
X_train_transformed = transformer.fit_transform(X_train)
X_test_transformed = transformer.transform(X_test)

In [117]:
# Replace 'hmv_transformer' with 'transformer' in the line where the error occurred
col_names = transformer.get_feature_names_out()

#In modified col names this code removes everything before the double underscore (), leaving just the base column names
modified_columns = [col.split('__')[-1] for col in col_names]

#Transforming Array into dataframes
X_train = pd.DataFrame(X_train_transformed, columns = modified_columns) # Use X_train_transformed here
X_test = pd.DataFrame(X_test_transformed, columns = modified_columns)
test_df = pd.DataFrame(X_test_transformed, columns = modified_columns)

In [118]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

# Define the column transformer with multiple preprocessing options
transformer = ColumnTransformer(
    transformers=[
        # Label encoding for non-ordered categorical features
        # (applied as a pipeline step, using OrdinalEncoder here as a substitute for LabelEncoder)
        ('label',
         OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1),
         ['estate_agency','salesperson','town']),  # Replace 'NonOrderedColumn' with your actual column names for label encoding

        # One-hot encoding for nominal categorical features
        ('onehot',
         OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore'),
         ['listing_purpose','has_garage','category_property','city', 'province'])  # Replace with your nominal categorical columns

    ],
    # Default action for columns not explicitly mentioned
    remainder='passthrough'  # Keeps the columns not specified as-is
)

# Apply the column transformer to training and testing data
X_train_transformed = transformer.fit_transform(X_train)
X_test_transformed = transformer.transform(X_test)

In [119]:
# Replace 'hmv_transformer' with 'transformer' in the line where the error occurred
col_names = transformer.get_feature_names_out()

#In modified col names this code removes everything before the double underscore (), leaving just the base column names
modified_columns = [col.split('__')[-1] for col in col_names]

#Transforming Array into dataframes
X_train = pd.DataFrame(X_train_transformed, columns = modified_columns) # Use X_train_transformed here
X_test = pd.DataFrame(X_test_transformed, columns = modified_columns)
test_df = pd.DataFrame(X_test_transformed, columns = modified_columns)

In [134]:
X_train

,estate_agency,salesperson,town,listing_purpose_For Sale,has_garage_True,category_property_Flat,category_property_House,category_property_Lower Portion,category_property_Room,category_property_Upper Portion,...,province_ Sindh,no_of_bathrooms,no_of_bedrooms,location_id,degree_of_latitude,degree_of_longitude,space_occupied,listing_year,listing_month,listing_day
0,3328.0,1443.0,327.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,5.2,4.0,1446,31.465422,74.385309,10,2019,7,23
1,563.0,4986.0,907.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,8.0,13.0,326,31.519709,74.32281,4,2019,5,3
2,4306.0,6462.0,302.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,5.0,4.0,5,24.825028,67.031579,8,2019,5,6
3,3328.0,1443.0,91.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,6.0,5.0,11704,31.329958,74.215204,3,2019,5,3
4,2126.0,5094.0,327.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,8.0,7.6,1447,31.462493,74.409342,20,2019,7,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129109,4890.0,5777.0,190.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1.0,3.0,3.0,9030,25.013673,67.31162,4,2019,7,12
129110,671.0,6088.0,327.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,6.0,4.0,3226,33.492591,73.301339,8,2019,7,3
129111,5125.0,7590.0,441.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,1.0,2.8,6692,24.918394,67.066677,4,2019,7,14
129112,3100.0,7770.0,1335.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,1.0,4.0,324,24.92252,67.103269,4,2019,7,17
129113,5118.0,405.0,189.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,7.0,6.0,1779,31.382805,74.188514,8,2019,7,11

In [135]:
X_test

,estate_agency,salesperson,town,listing_purpose_For Sale,has_garage_True,category_property_Flat,category_property_House,category_property_Lower Portion,category_property_Room,category_property_Upper Portion,...,province_ Sindh,no_of_bathrooms,no_of_bedrooms,location_id,degree_of_latitude,degree_of_longitude,space_occupied,listing_year,listing_month,listing_day
0,5477.0,831.0,530.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,5.0,4.0,6837,24.912026,67.130733,16,2019,5,18
1,2098.0,1244.0,327.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,8.0,7.0,1483,24.805045,67.064323,20,2019,7,9
2,1319.0,9877.0,190.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,1.0,5.0,4.0,8298,24.894076,67.027715,8,2019,6,27
3,4869.0,7653.0,190.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1.0,3.0,3.0,9030,25.020961,67.321172,4,2019,6,5
4,273.0,1714.0,1105.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,8.0,10638,31.346272,74.3782,20,2019,7,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32274,4597.0,4286.0,327.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,8.0,7.6,1483,24.805045,67.064323,20,2019,4,9
32275,1168.0,5699.0,102.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,4.350339,4.510115,4903,31.40896,73.037574,5,2019,7,17
32276,900.0,9276.0,327.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,11.0,8.0,1482,24.810265,67.043552,40,2019,7,3
32277,3799.0,4820.0,517.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,3.0,4948,31.399803,73.106446,7,2019,4,17
32278,1845.0,9033.0,1300.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,5.0,4.0,1356,31.420094,74.254174,5,2019,6,27

In [138]:

from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, BaggingRegressor, ExtraTreesRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [139]:

# Instantiate regression algorithms
lr = LinearRegression()
ridge = Ridge(alpha=1.0)
lasso = Lasso(alpha=0.1)
elastic_net = ElasticNet(alpha=0.1, l1_ratio=0.5)
dtr = DecisionTreeRegressor(max_depth=5)
knr = KNeighborsRegressor()
rfr = RandomForestRegressor(n_estimators=50, random_state=2)
abr = AdaBoostRegressor(n_estimators=50, random_state=2)
bgr = BaggingRegressor(n_estimators=50, random_state=2)
etr = ExtraTreesRegressor(n_estimators=50, random_state=2)
gbr = GradientBoostingRegressor(n_estimators=50, random_state=2)
xgbr = XGBRegressor(n_estimators=50, random_state=2)

In [140]:

# Dictionary of regression algorithms
regressors = {
    'Linear Regression': lr,
    'Ridge': ridge,
    'Lasso': lasso,
    'ElasticNet': elastic_net,
    'Decision Tree': dtr,
    'KNeighbors': knr,
    'Random Forest': rfr,
    'AdaBoost': abr,
    'Bagging': bgr,
    'ExtraTrees': etr,
    'GradientBoosting': gbr,
    # 'XGBoost': xgbr
}

In [141]:

def train_regressor(regressor, X_train, y_train, X_test, y_test):
    # Fit the model
    regressor.fit(X_train, y_train)
    # Predict on test data
    y_pred = regressor.predict(X_test)
    # Calculate regression evaluation metrics
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)
    rmse = np.sqrt(mse)  # Calculate RMSE


    return mae, mse, r2, rmse

In [142]:

# Initialize lists to store metrics
mae_scores = []
mse_scores = []
r2_scores = []
rmse_scores = []

# Iterate over regressors
for name, regressor in regressors.items():
    print(name)
    current_mae, current_mse, current_r2, current_rmse = train_regressor(regressor, X_train, y_train, X_test, y_test)

    print("For", name)
    print("Mean Absolute Error - ", current_mae)
    print("Mean Squared Error - ", current_mse)
    print("Root Mean Squared Error - ", current_rmse)
    print("R2 Score - ", current_r2)

    # Append metrics to respective lists
    mae_scores.append(current_mae)
    mse_scores.append(current_mse)
    r2_scores.append(current_r2)
    rmse_scores.append(current_rmse)

Linear Regression
For Linear Regression
Mean Absolute Error -  13410203.008428153
Mean Squared Error -  817590384950649.1
Root Mean Squared Error -  28593537.468292534
R2 Score -  0.23927121392772233
Ridge
For Ridge
Mean Absolute Error -  13410439.175990133
Mean Squared Error -  817681602511768.1
Root Mean Squared Error -  28595132.49683883
R2 Score -  0.23918634034577246
Lasso

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.516e+19, tolerance: 1.428e+16
  model = cd_fast.enet_coordinate_descent(

For Lasso
Mean Absolute Error -  13440357.242602807
Mean Squared Error -  819404205366680.0
Root Mean Squared Error -  28625237.2106622
R2 Score -  0.23758354070083665
ElasticNet
For ElasticNet
Mean Absolute Error -  13162315.8788368
Mean Squared Error -  832995294960122.5
Root Mean Squared Error -  28861657.869223703
R2 Score -  0.22493768126054603
Decision Tree
For Decision Tree
Mean Absolute Error -  5576071.746804673
Mean Squared Error -  291167580210432.1
Root Mean Squared Error -  17063633.265234932
R2 Score -  0.7290824795469499
KNeighbors
For KNeighbors
Mean Absolute Error -  9141737.026593141
Mean Squared Error -  599170036986907.4
Root Mean Squared Error -  24477950.016022734
R2 Score -  0.44250091087428234
Random Forest
For Random Forest
Mean Absolute Error -  2667310.854387355
Mean Squared Error -  126645357735587.14
Root Mean Squared Error -  11253681.963499198
R2 Score -  0.8821625461536
AdaBoost
For AdaBoost
Mean Absolute Error -  83798581.87740415
Mean Squared Error -  8673700178913318.0
Root Mean Squared Error -  93132701.98439063
R2 Score -  -7.0704635589102605
Bagging
For Bagging
Mean Absolute Error -  2657643.6301449267
Mean Squared Error -  122651705640031.95
Root Mean Squared Error -  11074823.052312482
R2 Score -  0.8858784485988447
ExtraTrees
For ExtraTrees
Mean Absolute Error -  2780740.7679505358
Mean Squared Error -  165221999451440.38
Root Mean Squared Error -  12853870.990928778
R2 Score -  0.8462688243542449
GradientBoosting
For GradientBoosting
Mean Absolute Error -  5493243.304172221
Mean Squared Error -  259890712281345.84
Root Mean Squared Error -  16121126.272110948
R2 Score -  0.7581841106446211