In [31]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

In [32]:
df2=pd.read_csv('hotel_bookings.csv')
df2.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [33]:
df = pd.read_csv('hotel_bookings.csv')
import pandas as pd

# Show all columns in the DataFrame
pd.set_option('display.max_columns', None)

# Optionally, show all rows (if needed)
pd.set_option('display.max_rows', None)

# If the DataFrame is very wide, consider adjusting column width
pd.set_option('display.max_colwidth', None)
df.sample(10)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
113304,City Hotel,0,16,2017,June,22,3,1,1,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,85.0,NaN,0,Transient,89.10,0,0,Check-Out,2017-06-05
70095,City Hotel,1,219,2017,June,23,9,1,2,2,0.0,0,BB,PRT,Offline TA/TO,TA/TO,0,0,0,A,A,0,Non Refund,20.0,NaN,0,Transient,105.00,0,0,Canceled,2017-04-21
17726,Resort Hotel,0,6,2015,October,42,13,1,5,2,0.0,0,BB,NLD,Online TA,TA/TO,0,0,0,D,D,1,No Deposit,240.0,NaN,0,Transient,73.33,1,3,Check-Out,2015-10-19
71509,City Hotel,1,315,2017,July,27,7,0,1,2,0.0,0,SC,USA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient,89.10,0,2,Canceled,2016-09-18
98142,City Hotel,0,17,2016,September,39,22,0,3,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,7.0,NaN,0,Transient,123.62,0,1,Check-Out,2016-09-25
108919,City Hotel,0,162,2017,April,13,1,2,1,2,0.0,0,BB,CN,Groups,TA/TO,0,0,0,A,A,0,No Deposit,296.0,NaN,0,Transient-Party,88.20,0,0,Check-Out,2017-04-04
32867,Resort Hotel,0,10,2017,February,6,6,1,1,3,0.0,0,Undefined,PRT,Groups,Corporate,0,0,0,A,C,0,No Deposit,NaN,507.0,0,Transient-Party,120.00,0,0,Check-Out,2017-02-08
111324,City Hotel,0,108,2017,May,18,4,2,3,2,0.0,0,SC,FRA,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,NaN,0,Transient,108.00,0,0,Check-Out,2017-05-09
112696,City Hotel,0,22,2017,May,21,26,0,1,3,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,NaN,0,Transient,230.00,0,0,Check-Out,2017-05-27
67110,City Hotel,1,159,2017,April,17,28,1,2,2,0.0,0,BB,BEL,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,NaN,0,Transient,130.50,0,0,Canceled,2016-11-28

In [34]:
df['total_stay_nights'] = df['stays_in_weekend_nights'] + df['stays_in_week_nights']

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 33 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
 32  total_stay_nights               119390 non-null  int64
dtypes: float64(4), int64(17), object(12)
memory usage: 30.1+ MB

In [36]:
df.drop(columns=['is_canceled', 'country', 'market_segment','company', 'arrival_date_year','arrival_date_month','arrival_date_week_number','arrival_date_day_of_month','reservation_status_date'], inplace=True)

In [37]:
df.shape

(119390, 24)

In [38]:
df.isnull().sum()

hotel                                 0
lead_time                             0
stays_in_weekend_nights               0
stays_in_week_nights                  0
adults                                0
children                              4
babies                                0
meal                                  0
distribution_channel                  0
is_repeated_guest                     0
previous_cancellations                0
previous_bookings_not_canceled        0
reserved_room_type                    0
assigned_room_type                    0
booking_changes                       0
deposit_type                          0
agent                             16340
days_in_waiting_list                  0
customer_type                         0
adr                                   0
required_car_parking_spaces           0
total_of_special_requests             0
reservation_status                    0
total_stay_nights                     0
dtype: int64

In [39]:
# Assuming 'target' is the column you want to predict
X = df.drop('reservation_status', axis=1)
y = df['reservation_status']

# Splitting into train and test sets (80/20 split)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [40]:

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer, KNNImputer

# Define the column transformer with multiple preprocessing options
transformer = ColumnTransformer(
    transformers=[
        # Imputation for missing values in numerical columns (KNNImputer)
        ('imputer_num_knn',
         KNNImputer(n_neighbors=5),
         ['agent','children']),  # Replace with your numerical columns for KNN imputation

    ],
    # Default action for columns not explicitly mentioned
    remainder='passthrough'  # Keeps the columns not specified as-is
)

# Apply the column transformer to training and testing data
X_train_transformed = transformer.fit_transform(X_train)
X_test_transformed = transformer.transform(X_test)

In [41]:

# Replace 'hmv_transformer' with 'transformer' in the line where the error occurred
col_names = transformer.get_feature_names_out()

#In modified col names this code removes everything before the double underscore (), leaving just the base column names
modified_columns = [col.split('__')[-1] for col in col_names]

#Transforming Array into dataframes
X_train = pd.DataFrame(X_train_transformed, columns = modified_columns) # Use X_train_transformed here
X_test = pd.DataFrame(X_test_transformed, columns = modified_columns)
test_df = pd.DataFrame(X_test_transformed, columns = modified_columns)

In [42]:
df['assigned_room_type'].value_counts()

assigned_room_type
A    74053
D    25322
E     7806
F     3751
G     2553
C     2375
B     2163
H      712
I      363
K      279
P       12
L        1
Name: count, dtype: int64

In [43]:

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

# Define the column transformer with multiple preprocessing options
transformer = ColumnTransformer(
    transformers=[
        # Label encoding for non-ordered categorical features
          # Ordinal encoding for ordered categorical features
        ('ordinal1',
         OrdinalEncoder(categories=[['P','L','H','G','F','E','D','C','B','A']], handle_unknown='use_encoded_value', unknown_value=-1),
         ['reserved_room_type']),  # Replace with your actual ordered categorical columns

          ('ordinal2',
         OrdinalEncoder(categories=[['P','L','K','I','H','G','F','E','D','C','B','A']], handle_unknown='use_encoded_value', unknown_value=-1),
         ['assigned_room_type']),  # Replace with your actual ordered categorical columns

        # One-hot encoding for nominal categorical features
        ('onehot',
         OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore'),
         ['hotel','meal','distribution_channel','deposit_type','customer_type'])  # Replace with your nominal categorical columns

    ],
    # Default action for columns not explicitly mentioned
    remainder='passthrough'  # Keeps the columns not specified as-is
)

# Apply the column transformer to training and testing data
X_train_transformed = transformer.fit_transform(X_train)
X_test_transformed = transformer.transform(X_test)

In [44]:
# Replace 'hmv_transformer' with 'transformer' in the line where the error occurred
col_names = transformer.get_feature_names_out()

#In modified col names this code removes everything before the double underscore (), leaving just the base column names
modified_columns = [col.split('__')[-1] for col in col_names]

#Transforming Array into dataframes
X_train = pd.DataFrame(X_train_transformed, columns = modified_columns) # Use X_train_transformed here
X_test = pd.DataFrame(X_test_transformed, columns = modified_columns)
test_df = pd.DataFrame(X_test_transformed, columns = modified_columns)


# Added
for col in X_train.columns:
    try:
        X_train[col] = pd.to_numeric(X_train[col])
    except ValueError:
        # If conversion to numeric fails, it might be a true categorical column
        # Handle these cases appropriately (e.g., using LabelEncoder)
        pass

for col in X_test.columns:
    try:
        X_test[col] = pd.to_numeric(X_test[col])
    except ValueError:
        pass

In [45]:
X_train.head()

,reserved_room_type,assigned_room_type,hotel_Resort Hotel,meal_FB,meal_HB,meal_SC,meal_Undefined,distribution_channel_Direct,distribution_channel_GDS,distribution_channel_TA/TO,distribution_channel_Undefined,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,agent,children,lead_time,stays_in_weekend_nights,stays_in_week_nights,adults,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,total_stay_nights
0,6.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,9.0,0.0,64,2,1,3,0,0,0,0,0,0,189.00,0,0,3
1,9.0,11.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,14.0,1.0,34,1,1,2,0,0,0,0,0,0,146.00,0,0,2
2,4.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,9.0,2.0,8,1,1,2,0,0,0,0,0,0,259.00,0,0,2
3,5.0,7.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,170.2,0.0,251,2,4,2,0,0,0,0,0,0,89.70,0,1,6
4,6.0,8.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,241.0,0.0,23,1,1,2,0,0,0,0,0,0,42.43,0,1,2

In [46]:
X_test.head()

,reserved_room_type,assigned_room_type,hotel_Resort Hotel,meal_FB,meal_HB,meal_SC,meal_Undefined,distribution_channel_Direct,distribution_channel_GDS,distribution_channel_TA/TO,distribution_channel_Undefined,deposit_type_Non Refund,deposit_type_Refundable,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,agent,children,lead_time,stays_in_weekend_nights,stays_in_week_nights,adults,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,total_stay_nights
0,4.0,6.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,250.0,0.0,203,2,5,2,0,0,0,0,4,0,66.8,0,0,7
1,9.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,9.0,0.0,82,0,3,2,0,0,0,0,0,0,76.5,0,0,3
2,9.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,220.0,0.0,25,0,3,3,0,0,0,0,2,0,60.0,0,1,3
3,9.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,9.0,0.0,1,0,1,1,0,0,0,0,0,0,95.0,0,0,1
4,9.0,11.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,9.0,0.0,70,2,2,2,0,0,0,0,0,0,108.0,0,0,4

In [47]:
from sklearn.preprocessing import LabelEncoder

# Initialize the LabelEncoder
label_encoder = LabelEncoder()

# Fit and transform the target column
y_train = label_encoder.fit_transform(y_train)

# If you have a test set and need to encode it as well
y_test = label_encoder.transform(y_test)

In [48]:
y_train = pd.DataFrame(y_train, columns=['reservation_status'])
y_test = pd.DataFrame(y_test, columns=['reservation_status'])

In [49]:
# SOME MODELS ARE VERY SENSITIVE TO NEGATIVE VALUES THEREFORE CHECKING FOR NULL VALUES AND HANDLING THEM BY MEAN

In [50]:
# Count the number of negative values in the entire DataFrame
negative_count = (X_train < 0).sum().sum()

print(f"Number of negative values in the DataFrame: {negative_count}")

Number of negative values in the DataFrame: 1

In [51]:
import numpy as np

# Replace negative values with column-wise mean
X_train = X_train.apply(lambda col: np.where(col < 0, col.mean(), col))

In [52]:
# Count the number of negative values in the entire DataFrame
negative_count = (X_train < 0).sum().sum()

print(f"Number of negative values in the DataFrame: {negative_count}")

Number of negative values in the DataFrame: 0

In [53]:
import warnings
warnings.filterwarnings("ignore")

In [54]:


from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score

In [55]:

svc = SVC(kernel='sigmoid', gamma=1.0)
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth=5)
lrc = LogisticRegression(solver='liblinear', penalty='l1')
rfc = RandomForestClassifier(n_estimators=50, random_state=2)
abc = AdaBoostClassifier(n_estimators=50, random_state=2)
bc = BaggingClassifier(n_estimators=50, random_state=2)
etc = ExtraTreesClassifier(n_estimators=50, random_state=2)
gbdt = GradientBoostingClassifier(n_estimators=50,random_state=2)
xgb = XGBClassifier(n_estimators=50,random_state=2)

In [56]:

clfs = {
    # 'SVC' : svc,
    'KN' : knc,
    'NB': mnb,
    'DT': dtc,
    'LR': lrc,
    'RF': rfc,
    'AdaBoost': abc,
    'BgC': bc,
    'ETC': etc,
    'GBDT':gbdt,
    'xgb':xgb

}

In [57]:

def train_classifier(clf,X_train,y_train,X_test,y_test):
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test,y_pred)
    precision = precision_score(y_test,y_pred, average='weighted')

    return accuracy,precision

In [58]:

accuracy_scores = []
precision_scores = []

for name,clf in clfs.items():

    print(name)

    current_accuracy,current_precision = train_classifier(clf, X_train,y_train,X_test,y_test)

    print("For ",name)
    print("Accuracy - ",current_accuracy)
    print("Precision - ",current_precision)

    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)

KN
For  KN
Accuracy -  0.7818494011223721
Precision -  0.7772688446453475
NB
For  NB
Accuracy -  0.3449618896054946
Precision -  0.5981089528309337
DT
For  DT
Accuracy -  0.767065918418628
Precision -  0.8283578519423175
LR
For  LR
Accuracy -  0.7974285953597454
Precision -  0.7988145503127395
RF
For  RF
Accuracy -  0.8644358824022113
Precision -  0.8617153131540453
AdaBoost
For  AdaBoost
Accuracy -  0.8155205628612111
Precision -  0.8153700778311032
BgC
For  BgC
Accuracy -  0.8602898065164587
Precision -  0.8575130632716761
ETC
For  ETC
Accuracy -  0.856604405729123
Precision -  0.8531745093743993
GBDT
For  GBDT
Accuracy -  0.8171957450372728
Precision -  0.8239164583354475
xgb
For  xgb
Accuracy -  0.8437055029734484
Precision -  0.8449425970418643