In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('training_data.csv')
df

,Date,Store_ID,Product_Category,Daily_Sales,Temperature,Rainfall,Humidity,Wind_Speed,Weather_Condition
0,2022-08-07 01:21:36,4,Electronics,4281,21.737444,18.782488,46.730572,8.767423,Rainy
1,2023-12-25 13:24:34,2,Beverages,3901,31.988128,9.259242,80.852541,16.878578,Rainy
2,2023-12-19 03:19:35,3,Beverages,1945,21.362592,6.553352,41.790911,20.649769,Sunny
3,2022-10-14 00:45:25,5,Beverages,1363,24.777099,19.369159,81.228123,24.480433,Sunny
4,2022-02-26 19:43:43,1,Clothing,3314,28.176562,14.463581,83.364466,12.877632,Sunny
...,...,...,...,...,...,...,...,...,...
14995,2023-02-10 06:53:47,4,Snacks,4243,NaN,2.086044,54.868794,22.686165,Sunny
14996,2022-04-18 13:43:38,2,Beverages,4283,20.595740,7.974800,71.362884,22.794143,Cloudy
14997,2022-12-01 12:56:45,4,Electronics,2789,22.222780,12.239800,73.784872,15.005188,Sunny
14998,2022-12-28 13:03:44,5,Beverages,1742,20.298747,0.672931,49.799249,23.446081,Sunny
14999,2023-08-07 16:10:37,3,Clothing,1050,18.379459,12.655174,88.741270,22.028189,Rainy

In [ ]:
df.sample(30)

,Date,Store_ID,Product_Category,Daily_Sales,Temperature,Rainfall,Humidity,Wind_Speed,Weather_Condition
11907,2023-06-23 11:08:04,2,Snacks,3481,24.653550,11.571558,76.305021,23.988323,Sunny
3025,2022-03-06 12:10:49,1,Beverages,1613,29.262237,5.290388,49.809171,86.596563,Rainy
4484,2023-02-02 18:24:44,2,Beverages,623,34.783437,1.997605,82.224041,17.385393,Rainy
11536,2022-05-22 06:20:45,5,Home Supplies,4062,34.984752,7.529161,67.045708,9.874822,Rainy
5009,2023-12-10 19:18:49,3,Beverages,490,28.319135,3.728680,89.515858,18.559236,Rainy
9014,2022-03-18 21:51:54,4,Snacks,1021,24.614099,10.548214,40.864699,12.976348,Cloudy
2601,2022-09-23 02:37:53,1,Snacks,3208,34.500573,2.595195,89.611819,22.451213,Cloudy
11023,2023-09-06 15:49:12,3,Beverages,3078,15.689711,0.686306,55.568093,19.621758,Rainy
11149,2022-09-25 02:27:25,2,Clothing,3155,21.644842,0.189134,52.795494,6.200635,Sunny
8208,2023-06-12 00:05:31,1,Beverages,3382,19.530346,18.572269,83.405656,23.277257,Cloudy
3702,2022-12-28 15:22:10,5,Electronics,2216,21.534589,11.711970,72.258056,22.974382,Rainy
2715,2023-11-07 02:36:25,3,Clothing,2700,20.677038,5.371806,62.891208,7.938668,Sunny
12573,2023-03-01 13:13:14,5,Electronics,3364,21.442308,7.462506,88.062687,21.807150,Cloudy
8759,2022-06-09 06:25:39,3,Beverages,2361,33.615259,2.984314,61.604011,20.186410,Cloudy
9563,2023-03-06 03:50:24,4,Electronics,1854,16.781314,3.263008,63.333805,7.929398,Sunny
6975,2023-06-16 04:36:38,2,Beverages,2639,22.820444,14.825206,40.057273,22.050856,Sunny
14813,2023-10-18 08:28:51,2,Clothing,3875,22.550051,3.399653,49.395735,7.905648,Sunny
14552,2023-03-24 12:00:12,3,Snacks,511,27.608684,18.250962,71.048117,18.065865,Cloudy
5027,2023-02-17 18:31:17,5,Clothing,4675,20.535268,8.334715,82.609503,17.235031,Sunny
11728,2022-03-31 21:14:26,2,Clothing,4861,18.853679,4.833475,55.741193,13.869053,Cloudy
7902,2022-07-25 19:10:25,5,Home Supplies,2996,32.954810,6.252938,88.068396,9.373927,Sunny
14424,2023-12-05 04:27:49,3,Home Supplies,541,26.033065,10.099695,78.785075,10.901760,Cloudy
3073,2023-04-25 04:34:56,3,Beverages,3228,30.652875,8.569323,56.590117,5.949497,Sunny
4993,2022-10-11 14:12:56,2,Clothing,3852,28.451773,13.873439,77.935433,22.759583,Cloudy
8359,2022-02-11 22:06:28,3,Home Supplies,4613,23.463914,6.591765,64.448569,7.770202,Sunny
10691,2022-07-15 03:35:44,3,Beverages,1731,20.355775,15.992053,84.138320,22.849926,Rainy
5649,2022-10-22 22:36:48,1,Home Supplies,1555,32.899796,NaN,52.725877,21.560680,Cloudy
1886,2022-12-30 11:54:22,5,Beverages,1346,17.377184,1.894548,76.206928,22.286901,Cloudy
2758,2023-12-03 00:18:17,1,Home Supplies,2178,23.007823,3.339498,60.713889,10.810727,Sunny
5440,2023-11-21 17:34:37,3,Electronics,743,27.455555,15.873466,61.754240,17.361740,Sunny

In [ ]:
from sklearn.impute import SimpleImputer

num_imputer = SimpleImputer(strategy='mean')
df['Temperature'] = num_imputer.fit_transform(df[['Temperature']])
df['Rainfall'] = num_imputer.fit_transform(df[['Rainfall']])

In [ ]:
df.isnull().sum()

Date                 0
Store_ID             0
Product_Category     0
Daily_Sales          0
Temperature          0
Rainfall             0
Humidity             0
Wind_Speed           0
Weather_Condition    0
dtype: int64

In [ ]:
df = pd.get_dummies(df, columns=['Product_Category',"Weather_Condition"])

df

,Date,Store_ID,Daily_Sales,Temperature,Rainfall,Humidity,Wind_Speed,Product_Category_Beverages,Product_Category_Clothing,Product_Category_Electronics,Product_Category_Home Supplies,Product_Category_Snacks,Weather_Condition_Cloudy,Weather_Condition_Rainy,Weather_Condition_Sunny
0,2022-08-07 01:21:36,4,4281,21.737444,18.782488,46.730572,8.767423,False,False,True,False,False,False,True,False
1,2023-12-25 13:24:34,2,3901,31.988128,9.259242,80.852541,16.878578,True,False,False,False,False,False,True,False
2,2023-12-19 03:19:35,3,1945,21.362592,6.553352,41.790911,20.649769,True,False,False,False,False,False,False,True
3,2022-10-14 00:45:25,5,1363,24.777099,19.369159,81.228123,24.480433,True,False,False,False,False,False,False,True
4,2022-02-26 19:43:43,1,3314,28.176562,14.463581,83.364466,12.877632,False,True,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,2023-02-10 06:53:47,4,4243,25.000291,2.086044,54.868794,22.686165,False,False,False,False,True,False,False,True
14996,2022-04-18 13:43:38,2,4283,20.595740,7.974800,71.362884,22.794143,True,False,False,False,False,True,False,False
14997,2022-12-01 12:56:45,4,2789,22.222780,12.239800,73.784872,15.005188,False,False,True,False,False,False,False,True
14998,2022-12-28 13:03:44,5,1742,20.298747,0.672931,49.799249,23.446081,True,False,False,False,False,False,False,True
14999,2023-08-07 16:10:37,3,1050,18.379459,12.655174,88.741270,22.028189,False,True,False,False,False,False,True,False

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])
df['year'] = df['Date'].dt.year
df['month'] = df['Date'].dt.month
df['day'] = df['Date'].dt.day

In [ ]:
df.sample(30)

,Date,Store_ID,Daily_Sales,Temperature,Rainfall,Humidity,Wind_Speed,Product_Category_Beverages,Product_Category_Clothing,Product_Category_Electronics,Product_Category_Home Supplies,Product_Category_Snacks,Weather_Condition_Cloudy,Weather_Condition_Rainy,Weather_Condition_Sunny,year,month,day
6922,2022-07-30 10:15:58,5,3035,18.831751,17.106526,53.997898,16.465936,False,True,False,False,False,False,True,False,2022,7,30
3470,2023-07-27 16:32:21,5,1555,17.851613,18.498482,58.534703,13.664665,False,True,False,False,False,False,False,True,2023,7,27
14135,2023-12-12 05:28:58,4,3605,32.958389,19.074623,72.485203,17.984809,False,True,False,False,False,False,True,False,2023,12,12
8903,2023-08-08 06:03:28,1,869,32.621546,4.617275,62.000858,8.134745,False,False,False,False,True,True,False,False,2023,8,8
4850,2023-11-22 16:50:12,4,4943,16.368724,8.423299,85.388340,24.189063,False,False,True,False,False,True,False,False,2023,11,22
9047,2022-07-30 16:26:19,1,942,30.933539,14.013363,72.861675,15.778913,False,False,False,True,False,False,False,True,2022,7,30
2655,2022-11-06 10:38:29,4,654,25.004093,4.695044,79.844607,7.568301,True,False,False,False,False,False,False,True,2022,11,6
12864,2023-10-09 22:07:01,4,843,24.128957,19.084111,74.465325,18.340778,False,False,False,True,False,True,False,False,2023,10,9
6193,2022-03-12 02:03:35,5,3787,19.605274,3.289305,76.372629,9.048830,False,False,True,False,False,True,False,False,2022,3,12
14336,2023-03-15 11:58:31,1,2817,34.696628,17.643528,71.012956,11.876335,False,False,False,False,True,False,False,True,2023,3,15
3231,2022-02-06 01:08:18,4,3838,17.843391,0.495373,70.818244,23.286152,False,False,False,False,True,False,False,True,2022,2,6
4277,2023-12-24 12:06:00,4,3792,22.188273,17.860612,77.350993,17.419919,False,True,False,False,False,False,True,False,2023,12,24
12403,2023-11-12 09:55:26,5,4823,28.092034,5.125272,68.304098,18.944495,False,False,False,False,True,True,False,False,2023,11,12
9241,2022-06-17 23:48:42,2,3321,28.619476,15.696304,82.596035,10.071795,False,False,False,True,False,False,False,True,2022,6,17
854,2022-06-19 09:57:16,4,1307,20.554252,7.817051,78.233690,17.335276,False,False,False,True,False,False,False,True,2022,6,19
12240,2023-10-06 06:22:06,2,2757,29.125689,3.937245,41.209455,22.129100,False,False,False,False,True,False,False,True,2023,10,6
2644,2023-04-25 00:01:12,5,971,28.046341,18.234284,69.094315,20.078060,False,True,False,False,False,True,False,False,2023,4,25
3188,2023-09-28 03:06:23,4,279,19.267242,0.284243,53.780551,13.034670,False,True,False,False,False,False,False,True,2023,9,28
11281,2023-05-31 10:10:33,1,2823,30.196410,12.940375,62.676133,21.307681,False,True,False,False,False,True,False,False,2023,5,31
4696,2023-01-08 10:35:04,5,3624,15.042817,12.643652,75.663097,11.284231,False,False,False,False,True,True,False,False,2023,1,8
4941,2023-06-12 01:21:35,1,718,17.692638,19.889476,45.311665,14.503083,False,False,False,True,False,False,True,False,2023,6,12
5419,2023-05-29 17:18:54,4,1620,20.636456,3.910497,65.147263,9.428381,False,False,True,False,False,False,False,True,2023,5,29
1828,2023-05-10 15:39:46,1,4041,22.042872,9.996722,80.545240,21.403652,False,False,False,False,True,False,False,True,2023,5,10
14308,2022-11-21 05:34:29,4,4095,25.217239,1.008434,84.648373,18.167338,False,False,True,False,False,False,False,True,2022,11,21
13103,2023-11-05 04:02:24,2,3514,16.566058,11.133042,63.478883,12.999556,False,False,False,False,True,True,False,False,2023,11,5
6647,2023-04-29 18:20:25,3,895,34.365313,8.435676,62.604553,14.291244,False,True,False,False,False,False,False,True,2023,4,29
5720,2023-02-14 22:26:07,3,3243,21.685909,19.406513,76.635608,11.742718,False,False,False,True,False,True,False,False,2023,2,14
11115,2022-08-21 22:31:17,5,2921,20.119070,5.981917,79.919115,6.472487,False,True,False,False,False,False,False,True,2022,8,21
7161,2022-06-19 12:45:12,3,3754,21.008095,4.883866,73.434354,20.744809,False,False,False,False,True,True,False,False,2022,6,19
556,2023-03-20 19:15:05,3,1526,31.433719,18.318531,41.670349,16.460008,False,True,False,False,False,False,True,False,2023,3,20

In [ ]:
df.shape

(15000, 18)

In [ ]:
df.corr()

,Date,Store_ID,Daily_Sales,Temperature,Rainfall,Humidity,Wind_Speed,Product_Category_Beverages,Product_Category_Clothing,Product_Category_Electronics,Product_Category_Home Supplies,Product_Category_Snacks,Weather_Condition_Cloudy,Weather_Condition_Rainy,Weather_Condition_Sunny,year,month,day
Date,1.000000,-0.010082,0.007859,-0.013236,-0.009526,0.000107,-0.003410,0.003982,-0.000220,-0.007765,0.007426,-0.003431,0.004147,-0.008873,0.004736,0.864626,0.493871,0.050477
Store_ID,-0.010082,1.000000,0.003696,-0.000668,-0.005716,0.010939,-0.005714,-0.014926,0.001692,-0.001664,0.005568,0.009117,-0.015977,0.012439,0.003517,-0.010147,-0.003048,0.006625
Daily_Sales,0.007859,0.003696,1.000000,-0.000498,0.010404,0.001954,-0.006150,0.003044,-0.007096,0.001439,-0.003426,0.006026,0.008597,0.000660,-0.009252,0.008523,0.002160,-0.014931
Temperature,-0.013236,-0.000668,-0.000498,1.000000,-0.001928,-0.009965,-0.011910,0.007096,0.003314,-0.010582,0.003188,-0.002950,-0.005618,0.014117,-0.008514,-0.011954,-0.005982,0.001763
Rainfall,-0.009526,-0.005716,0.010404,-0.001928,1.000000,0.001463,-0.010648,0.010028,0.011687,-0.003636,-0.007263,-0.010561,-0.002379,0.005070,-0.002696,-0.009332,-0.002120,-0.007700
Humidity,0.000107,0.010939,0.001954,-0.009965,0.001463,1.000000,-0.002390,-0.009556,0.013784,-0.004696,-0.006295,0.006760,-0.007047,-0.002919,0.009963,-0.011212,0.020815,-0.012808
Wind_Speed,-0.003410,-0.005714,-0.006150,-0.011910,-0.010648,-0.002390,1.000000,-0.001297,-0.006842,0.014992,-0.003960,-0.002889,0.000909,0.009406,-0.010322,-0.002134,-0.003538,0.005441
Product_Category_Beverages,0.003982,-0.014926,0.003044,0.007096,0.010028,-0.009556,-0.001297,1.000000,-0.244500,-0.246402,-0.249735,-0.248659,-0.008421,0.003825,0.004587,0.003095,0.001532,0.011946
Product_Category_Clothing,-0.000220,0.001692,-0.007096,0.003314,0.011687,0.013784,-0.006842,-0.244500,1.000000,-0.247968,-0.251322,-0.250239,0.017573,-0.011464,-0.006088,0.002383,-0.004519,0.000034
Product_Category_Electronics,-0.007765,-0.001664,0.001439,-0.010582,-0.003636,-0.004696,0.014992,-0.246402,-0.247968,1.000000,-0.253276,-0.252185,-0.005969,0.018138,-0.012188,-0.008834,0.001176,-0.017183
Product_Category_Home Supplies,0.007426,0.005568,-0.003426,0.003188,-0.007263,-0.006295,-0.003960,-0.249735,-0.251322,-0.253276,1.000000,-0.255596,0.005099,-0.013809,0.008725,0.006551,0.003562,-0.000512
Product_Category_Snacks,-0.003431,0.009117,0.006026,-0.002950,-0.010561,0.006760,-0.002889,-0.248659,-0.250239,-0.252185,-0.255596,1.000000,-0.008268,0.003382,0.004878,-0.003193,-0.001777,0.005789
Weather_Condition_Cloudy,0.004147,-0.015977,0.008597,-0.005618,-0.002379,-0.007047,0.000909,-0.008421,0.017573,-0.005969,0.005099,-0.008268,1.000000,-0.500073,-0.498876,0.008503,-0.006392,-0.000847
Weather_Condition_Rainy,-0.008873,0.012439,0.000660,0.014117,0.005070,-0.002919,0.009406,0.003825,-0.011464,0.018138,-0.013809,0.003382,-0.500073,1.000000,-0.501050,-0.010046,0.001106,-0.017424
Weather_Condition_Sunny,0.004736,0.003517,-0.009252,-0.008514,-0.002696,0.009963,-0.010322,0.004587,-0.006088,-0.012188,0.008725,0.004878,-0.498876,-0.501050,1.000000,0.001557,0.005280,0.018285
year,0.864626,-0.010147,0.008523,-0.011954,-0.009332,-0.011212,-0.002134,0.003095,0.002383,-0.008834,0.006551,-0.003193,0.008503,-0.010046,0.001557,1.000000,-0.007837,-0.001131
month,0.493871,-0.003048,0.002160,-0.005982,-0.002120,0.020815,-0.003538,0.001532,-0.004519,0.001176,0.003562,-0.001777,-0.006392,0.001106,0.005280,-0.007837,1.000000,0.019335
day,0.050477,0.006625,-0.014931,0.001763,-0.007700,-0.012808,0.005441,0.011946,0.000034,-0.017183,-0.000512,0.005789,-0.000847,-0.017424,0.018285,-0.001131,0.019335,1.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Date                            15000 non-null  datetime64[ns]
 1   Store_ID                        15000 non-null  int64
 2   Daily_Sales                     15000 non-null  int64
 3   Temperature                     15000 non-null  float64
 4   Rainfall                        15000 non-null  float64
 5   Humidity                        15000 non-null  float64
 6   Wind_Speed                      15000 non-null  float64
 7   Product_Category_Beverages      15000 non-null  bool
 8   Product_Category_Clothing       15000 non-null  bool
 9   Product_Category_Electronics    15000 non-null  bool
 10  Product_Category_Home Supplies  15000 non-null  bool
 11  Product_Category_Snacks         15000 non-null  bool
 12  Weather_Condition_Cloudy        15000 non-null  bool
 13  Weather_Condition_Rainy         15000 non-null  bool
 14  Weather_Condition_Sunny         15000 non-null  bool
 15  year                            15000 non-null  int32
 16  month                           15000 non-null  int32
 17  day                             15000 non-null  int32
dtypes: bool(8), datetime64[ns](1), float64(4), int32(3), int64(2)
memory usage: 1.1 MB

In [ ]:
df.describe()

,Date,Store_ID,Daily_Sales,Temperature,Rainfall,Humidity,Wind_Speed,year,month,day
count,15000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,2023-01-03 00:44:18.875866624,3.014733,2648.499133,25.000291,9.996722,64.951936,15.712970,2022.503000,6.553733,15.804600
min,2022-01-01 00:34:26,1.000000,100.000000,15.000105,0.000392,40.003022,5.002048,2022.000000,1.000000,1.000000
25%,2022-07-06 07:20:29.750000128,2.000000,1337.000000,20.067684,5.018633,52.480395,10.017546,2022.000000,4.000000,8.000000
50%,2023-01-02 16:47:11,3.000000,2554.500000,25.000291,9.996722,64.934609,15.126216,2023.000000,7.000000,16.000000
75%,2023-07-04 01:46:12.500000,4.000000,3797.250000,30.001114,14.987337,77.361395,20.322789,2023.000000,10.000000,23.000000
max,2023-12-31 22:43:55,5.000000,19995.000000,34.997210,19.997745,89.993190,99.265949,2023.000000,12.000000,31.000000
std,NaN,1.421402,1809.280287,5.759275,5.760129,14.430245,8.655761,0.500008,3.452348,8.808617

In [ ]:
df = df[df['Wind_Speed'] < 50]
df = df[df['Daily_Sales'] < 10000]
df.sample(30)

,Date,Store_ID,Daily_Sales,Temperature,Rainfall,Humidity,Wind_Speed,Product_Category_Beverages,Product_Category_Clothing,Product_Category_Electronics,Product_Category_Home Supplies,Product_Category_Snacks,Weather_Condition_Cloudy,Weather_Condition_Rainy,Weather_Condition_Sunny,year,month,day
7421,2023-12-02 05:27:40,2,2958,18.955540,17.976810,49.016365,11.872976,True,False,False,False,False,False,False,True,2023,12,2
2000,2022-06-09 02:52:30,3,1638,23.898004,16.872145,69.766668,17.835813,False,False,True,False,False,True,False,False,2022,6,9
8063,2023-05-02 22:35:03,3,2946,26.802416,1.698654,67.050667,10.246781,False,False,False,True,False,True,False,False,2023,5,2
4499,2022-04-09 18:52:15,4,340,19.244966,17.523655,43.118231,9.466172,False,False,True,False,False,True,False,False,2022,4,9
10862,2022-05-31 02:10:56,1,3103,24.014264,7.714374,78.263754,24.345375,False,False,False,True,False,False,True,False,2022,5,31
7361,2023-12-15 17:15:12,2,4972,22.412165,19.941940,78.628074,10.981920,False,False,True,False,False,False,True,False,2023,12,15
10802,2023-10-13 04:34:44,3,1718,15.656845,4.416206,81.716563,22.605827,False,False,False,False,True,True,False,False,2023,10,13
12332,2023-10-12 20:31:47,1,2205,26.610821,18.111977,51.477029,16.665062,False,False,False,True,False,False,False,True,2023,10,12
5365,2022-11-13 02:39:16,2,2729,33.649792,4.010393,65.246403,11.423406,False,False,False,True,False,True,False,False,2022,11,13
2994,2023-03-10 18:25:53,2,2668,33.451856,11.566003,62.124799,10.233254,False,False,False,True,False,False,True,False,2023,3,10
5252,2022-01-17 19:38:19,3,933,28.112425,6.320146,53.117183,19.560267,False,False,False,True,False,False,False,True,2022,1,17
6774,2022-07-17 18:42:52,2,1563,28.689609,7.368480,55.636601,20.165922,True,False,False,False,False,False,True,False,2022,7,17
12987,2023-03-04 17:44:06,1,637,17.047074,3.413172,66.297429,13.941395,False,False,False,True,False,False,True,False,2023,3,4
7231,2023-11-20 02:25:33,3,2752,18.730222,14.646038,79.879907,9.072289,False,False,False,True,False,False,False,True,2023,11,20
12795,2022-05-11 17:47:13,1,567,16.298998,9.996722,44.765374,10.860554,False,True,False,False,False,False,True,False,2022,5,11
2701,2022-06-15 09:09:39,1,2531,22.927663,6.414901,68.169595,21.120861,False,False,False,True,False,False,False,True,2022,6,15
1692,2022-07-03 11:18:19,4,965,25.483777,16.501336,55.778703,8.083852,False,False,True,False,False,False,True,False,2022,7,3
7564,2023-10-26 14:19:42,1,2779,33.936335,17.089542,70.447257,21.102528,False,True,False,False,False,False,True,False,2023,10,26
4286,2023-12-22 20:18:44,4,4833,24.601649,18.831902,89.289096,16.284013,False,False,False,True,False,False,False,True,2023,12,22
7630,2022-12-25 18:18:18,5,2391,27.205507,19.356313,51.243410,15.846104,False,True,False,False,False,False,False,True,2022,12,25
10527,2023-10-27 10:59:25,1,2088,28.820981,15.855317,74.893163,11.241565,False,False,True,False,False,False,False,True,2023,10,27
8683,2023-01-22 02:45:00,4,411,15.634393,5.396217,77.255735,7.288851,False,False,False,True,False,True,False,False,2023,1,22
6427,2022-09-03 13:16:12,3,3022,25.782541,8.308990,54.728137,5.620691,False,True,False,False,False,False,True,False,2022,9,3
5643,2023-08-12 10:30:41,1,1871,19.873258,1.811418,87.658564,9.601070,False,False,False,True,False,True,False,False,2023,8,12
6726,2023-10-16 10:52:29,5,3215,16.873233,11.609613,43.201361,21.032626,False,False,False,True,False,True,False,False,2023,10,16
13761,2023-10-13 00:07:51,3,3545,25.000291,3.521602,49.524484,8.881153,False,True,False,False,False,False,False,True,2023,10,13
6615,2022-03-18 07:31:24,2,2862,17.861809,19.126809,85.063933,22.974856,False,False,False,False,True,False,False,True,2022,3,18
8697,2023-05-27 08:19:21,3,3347,18.595703,14.947025,55.219344,5.670002,False,False,False,True,False,True,False,False,2023,5,27
11765,2022-12-06 13:01:13,5,2753,22.915692,13.921093,40.718997,13.451878,False,True,False,False,False,False,False,True,2022,12,6
6761,2022-03-08 23:06:21,5,3773,33.000394,3.954512,44.794503,20.640879,False,True,False,False,False,False,False,True,2022,3,8

In [ ]:
df.drop('Date', axis=1, inplace=True)

In [ ]:
df2 = pd.read_csv('testing_data.csv')

df2 = pd.get_dummies(df2, columns=['Product_Category',"Weather_Condition"])
df2['Date'] = pd.to_datetime(df2['Date'])
df2['year'] = df2['Date'].dt.year
df2['month'] = df2['Date'].dt.month
df2['day'] = df2['Date'].dt.day

df2.drop('Date', axis=1, inplace=True)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Store_ID                        300 non-null    int64
 1   Temperature                     300 non-null    float64
 2   Rainfall                        300 non-null    float64
 3   Humidity                        300 non-null    float64
 4   Wind_Speed                      300 non-null    float64
 5   Product_Category_Beverages      300 non-null    bool
 6   Product_Category_Clothing       300 non-null    bool
 7   Product_Category_Electronics    300 non-null    bool
 8   Product_Category_Home Supplies  300 non-null    bool
 9   Product_Category_Snacks         300 non-null    bool
 10  Weather_Condition_Cloudy        300 non-null    bool
 11  Weather_Condition_Rainy         300 non-null    bool
 12  Weather_Condition_Sunny         300 non-null    bool
 13  year                            300 non-null    int32
 14  month                           300 non-null    int32
 15  day                             300 non-null    int32
dtypes: bool(8), float64(4), int32(3), int64(1)
memory usage: 17.7 KB

In [ ]:
from sklearn.model_selection import train_test_split

# X = df.drop('Daily_Sales', axis=1)
# y = df['Daily_Sales']

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train = df.drop('Daily_Sales', axis=1)
y_train = df['Daily_Sales']


X_test = df2

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

In [ ]:


lrg = LinearRegression()
dtg = DecisionTreeRegressor()

lrg_model = lrg.fit(X_train, y_train)
dtg_model = dtg.fit(X_train, y_train)

lrg_pred = lrg_model.predict(X_test)
dtg_pred = dtg_model.predict(X_test)


lrg_pred

array([2529.5857206 , 2523.50788541, 2600.46593694, 2588.94853183,
       2525.75394146, 2535.20125881, 2551.22038658, 2527.07210653,
       2573.3247731 , 2578.26973581, 2591.05451919, 2573.4946621 ,
       2509.80069134, 2509.34654665, 2527.48243515, 2558.86410211,
       2513.52306338, 2541.9070987 , 2479.72008499, 2546.38508803,
       2516.49568784, 2560.09658499, 2594.73754796, 2504.10937534,
       2576.69219981, 2506.71530096, 2527.11808285, 2510.50339307,
       2577.63914136, 2544.47632343, 2567.86591622, 2565.35388451,
       2514.09861842, 2530.14275937, 2574.14397833, 2555.50593623,
       2547.3670849 , 2472.66869882, 2497.63752114, 2510.61289514,
       2515.59685881, 2474.96389923, 2565.75042999, 2578.57189786,
       2601.48353207, 2524.96307448, 2526.04911953, 2537.64883224,
       2560.8940312 , 2607.70334384, 2525.58135241, 2530.72932765,
       2525.85915348, 2522.23742502, 2520.62154393, 2513.85520952,
       2520.09426041, 2582.87935521, 2565.00483969, 2571.37033377,
       2615.74769545, 2551.65048788, 2584.37264398, 2574.23586349,
       2496.05598636, 2580.56327787, 2489.00518359, 2495.70524367,
       2546.99081183, 2520.15581699, 2550.86566072, 2551.7712612 ,
       2533.67159228, 2526.14531425, 2565.93052877, 2475.23534222,
       2512.83852347, 2498.87910577, 2558.05479127, 2571.01050759,
       2497.15647763, 2533.25527466, 2578.07833753, 2567.33663215,
       2575.38206471, 2617.71209286, 2554.28163733, 2525.81366758,
       2570.62280232, 2580.57942271, 2517.63759438, 2505.63947087,
       2510.10333113, 2558.89893193, 2569.54007764, 2460.04255417,
       2573.60311031, 2561.9592386 , 2505.81388742, 2551.26732459,
       2506.52222748, 2550.86078947, 2578.20284719, 2589.91814765,
       2503.66608795, 2578.56010734, 2592.55036929, 2556.12277626,
       2492.20677505, 2586.03174842, 2590.31926647, 2552.98377524,
       2562.43402775, 2556.67614223, 2552.06653596, 2570.82917476,
       2578.48689615, 2615.05332159, 2553.77810305, 2553.2224301 ,
       2551.30148531, 2529.73369456, 2587.40113674, 2573.28420775,
       2528.75501213, 2482.00363919, 2537.87921207, 2592.82805661,
       2585.45576884, 2532.49146027, 2516.19510034, 2532.56800954,
       2479.65736482, 2517.0058634 , 2556.35396436, 2521.39051455,
       2555.64586155, 2483.34031618, 2513.07720464, 2489.26330156,
       2572.71555488, 2582.5618837 , 2536.3996797 , 2503.38198543,
       2549.73695152, 2627.36897065, 2506.43568863, 2525.34820309,
       2553.78793329, 2526.59691654, 2572.87931704, 2467.08873216,
       2545.22111732, 2530.08953352, 2500.56781541, 2537.49090868,
       2530.9187272 , 2529.17680707, 2489.38234062, 2542.01736646,
       2514.57192792, 2547.43245921, 2553.83761227, 2525.96814267,
       2503.22725093, 2561.16573165, 2535.91057448, 2562.27474485,
       2525.25434296, 2543.18280459, 2519.98755292, 2527.40654279,
       2545.48310275, 2542.22911316, 2564.48736452, 2508.99197715,
       2534.08024614, 2544.03666743, 2579.21295382, 2486.18542501,
       2581.26957968, 2518.06600732, 2532.74601502, 2521.5566935 ,
       2514.79104087, 2553.28209599, 2560.56403623, 2500.60010028,
       2529.31418768, 2512.55694463, 2544.75441661, 2601.54035859,
       2569.34742052, 2586.81223814, 2602.66497034, 2525.67763006,
       2531.71420033, 2540.68978737, 2508.7834904 , 2554.85846043,
       2594.49211864, 2523.62751087, 2458.88385397, 2552.22426383,
       2523.38705546, 2574.66542395, 2577.21112653, 2518.8558835 ,
       2601.85938184, 2468.36266486, 2532.6798391 , 2573.20433765,
       2507.55610881, 2548.21310836, 2608.53961804, 2565.59947426,
       2555.33220993, 2585.48288398, 2571.11397298, 2563.73303362,
       2569.86279999, 2472.88014439, 2522.00580707, 2524.65009281,
       2506.93413871, 2531.34396648, 2535.54417645, 2573.53088819,
       2550.39356262, 2552.85331144, 2590.91330176, 2552.484011  ,
       2516.76102129, 2558.45249857, 2527.39452369, 2521.57804979,
       2463.04985941, 2584.65901453, 2570.01695401, 2580.11948843,
       2545.22492113, 2570.93441086, 2520.18810747, 2486.50038581,
       2546.19862631, 2559.29969656, 2508.65042751, 2513.74092484,
       2552.06252888, 2593.1176286 , 2567.39078968, 2577.87184136,
       2548.80157071, 2502.18030955, 2514.39254173, 2542.42695097,
       2524.43424868, 2584.98544345, 2545.59141766, 2527.64130475,
       2553.1022888 , 2533.70008987, 2560.17844172, 2569.31522223,
       2559.68886631, 2620.64438879, 2513.75511834, 2576.71427156,
       2568.94957161, 2493.89285805, 2545.0301817 , 2536.97596876,
       2526.72014979, 2589.56270939, 2535.19729954, 2546.0598136 ,
       2561.77084913, 2562.24549779, 2529.57742921, 2558.71803413,
       2481.83551714, 2616.81212565, 2522.12753485, 2575.1762061 ,
       2487.34156191, 2591.24542775, 2483.23742754, 2580.31184673,
       2559.18476202, 2531.68606031, 2530.17873453, 2504.01886554,
       2576.44105777, 2561.7024172 , 2539.100695  , 2531.60765714,
       2521.09582238, 2544.72393458, 2559.34804393, 2615.02378555])

In [ ]:
dtg_pred

array([4277., 1353.,  759., 4912., 4430., 4813., 1297., 2767., 4012.,
       4865., 4804., 4754., 2024., 1271., 4240., 1715., 4446., 2544.,
       3432., 3069.,  362.,  809., 2243., 1323., 1594., 4369.,  181.,
       1376.,  628., 3781., 4775., 2893.,  971., 2428., 3718.,  308.,
       1688.,  134., 4229., 4225., 2641.,  694., 4132., 1215., 4385.,
        690.,  752., 4277., 2981., 2842., 2927., 2343.,  722., 2975.,
       4298., 3097., 1007.,  148., 2358., 2221., 1767., 4417., 1306.,
       2930., 4378., 2302., 2700., 2768., 4644., 1645., 3361., 4176.,
       1272., 4840., 1828., 1560.,  218., 1137., 4364., 2645., 2298.,
        114., 3134., 3274.,  408., 1133., 2493., 1251., 4509.,  376.,
       1124., 2707., 1881., 3722., 4192., 2184., 3710., 1584., 2629.,
       3992., 1068.,  245., 2584.,  973.,  936., 3533., 2789., 3238.,
        215.,  857., 2852., 3876., 4169., 3700., 2258., 1722., 3506.,
        387.,  100., 4954., 4844., 1999., 3229., 3506.,  117., 2810.,
        452.,  354., 2327.,  346., 2862., 1500., 3724., 4487., 2444.,
       2534., 3875., 4489., 1373., 4353., 3759.,  454., 3710., 1050.,
       3857.,  889., 4890., 2193.,  527., 1387., 2786., 2362., 2534.,
       3666., 4569., 4813., 1392., 3885., 3305., 2787., 2638., 1904.,
       3033., 2032.,  722., 2890., 3921., 3085., 1833.,  929.,  846.,
       2382.,  230., 3243., 3996., 4271., 2241., 1435., 3141., 2204.,
        684., 4149.,  745., 1365., 2191., 4813.,  123., 3096., 2384.,
       4667., 2667., 4666., 2782., 3496.,  580., 4719., 2548., 4167.,
       4525., 3003.,  410.,  628.,  689.,  760.,  634., 1305.,  320.,
       2533., 2878., 1498.,  713., 1046., 2020., 1676., 2122.,  507.,
        808.,  129.,  408.,  415., 3918., 2219.,  634., 3750., 3382.,
       2687., 1979., 4174., 2473., 2036., 1271.,  305., 3459., 4479.,
       1482., 4696.,  870., 4081., 1056., 3171., 3469., 1464., 1682.,
        848., 4112.,  316., 4533.,  132.,  239.,  524., 1024., 4541.,
       4389., 3072., 1238.,  588., 4134., 4243., 4602., 1693.,  570.,
       2538., 1876.,  949.,  754., 4526., 3743.,  186., 3543.,  673.,
       2095.,  103., 2246., 2217., 3475., 2564., 4007., 2353., 4944.,
       1813., 1584., 3151., 3802., 4961.,  220., 1744., 3398., 1420.,
        810.,  255., 1328., 1412., 4057., 1559., 4762., 1586.,  946.,
        205., 4417., 4702.])

In [ ]:
df5 = pd.read_csv('testing_data.csv')

df5['Predicted_Sales'] = dtg_pred
df5

,Date,Store_ID,Product_Category,Temperature,Rainfall,Humidity,Wind_Speed,Weather_Condition,Predicted_Sales
0,2022-06-22 20:49:43,3,Beverages,26.106182,5.343010,51.342935,10.073698,Rainy,4277.0
1,2022-01-08 23:00:39,2,Clothing,23.790370,14.283077,80.411678,15.341726,Rainy,1353.0
2,2023-04-18 10:32:28,2,Electronics,29.235643,16.219582,82.512688,9.985604,Cloudy,759.0
3,2023-12-15 23:47:44,4,Electronics,23.004811,16.103989,85.340375,17.684905,Cloudy,4912.0
4,2022-06-12 19:11:12,2,Snacks,34.966646,5.771478,68.244366,16.907885,Sunny,4430.0
...,...,...,...,...,...,...,...,...,...
295,2022-09-04 16:26:17,4,Clothing,24.397059,13.096491,66.025190,23.001438,Cloudy,1586.0
296,2023-04-24 10:50:53,2,Clothing,22.435821,10.927929,50.437780,16.588998,Rainy,946.0
297,2023-12-23 09:32:05,2,Snacks,23.429316,8.158053,64.838451,15.983606,Sunny,205.0
298,2022-03-03 22:18:55,2,Snacks,32.851493,11.626480,72.356692,8.293086,Sunny,4417.0
299,2023-05-12 05:56:33,1,Snacks,33.294332,8.027832,51.733761,5.100002,Cloudy,4702.0

In [ ]:
df5.sample(30)

,Date,Store_ID,Product_Category,Temperature,Rainfall,Humidity,Wind_Speed,Weather_Condition,Predicted_Sales
262,2023-07-11 14:27:53,4,Beverages,27.919968,7.803250,81.244747,24.576555,Cloudy,1876.0
247,2022-05-21 17:15:48,4,Electronics,21.337721,3.785098,63.075732,20.158930,Sunny,132.0
154,2023-12-31 19:08:41,2,Clothing,21.226276,7.068032,46.147084,13.769794,Sunny,4569.0
133,2022-10-23 03:23:41,5,Electronics,21.608722,18.284317,85.138747,14.224649,Sunny,4487.0
99,2023-10-11 18:20:06,1,Clothing,19.853420,13.723621,43.643724,19.820039,Rainy,3992.0
298,2022-03-03 22:18:55,2,Snacks,32.851493,11.626480,72.356692,8.293086,Sunny,4417.0
257,2023-12-12 07:24:43,4,Snacks,17.519835,2.628127,67.512910,20.446385,Cloudy,4243.0
66,2022-09-23 02:22:47,4,Clothing,25.948570,10.432041,84.794785,10.534239,Rainy,2700.0
62,2023-05-31 16:32:28,1,Snacks,26.064119,4.367317,41.059341,7.476678,Cloudy,1306.0
61,2023-07-13 04:40:21,3,Beverages,26.568826,15.063537,71.641101,21.280314,Rainy,4417.0
45,2022-09-11 02:23:09,5,Beverages,24.952365,6.141756,49.368543,19.547469,Rainy,690.0
268,2023-12-09 21:16:14,3,Snacks,16.373874,1.118075,51.200688,16.943988,Sunny,3543.0
93,2022-12-10 21:15:12,1,Clothing,26.186841,3.303689,62.635679,6.926968,Cloudy,3722.0
199,2022-10-10 12:40:47,2,Beverages,16.664508,15.828434,45.983961,21.377342,Rainy,3003.0
256,2022-08-28 03:32:44,1,Home Supplies,20.820730,15.364204,87.356892,9.604555,Rainy,4134.0
183,2022-01-25 06:14:19,4,Snacks,25.877875,16.281891,63.835359,14.832464,Rainy,1365.0
148,2023-10-13 21:24:57,5,Electronics,25.786745,2.275559,87.019834,9.668599,Sunny,527.0
8,2023-05-01 18:50:41,5,Home Supplies,26.905553,4.953721,58.254286,5.344348,Rainy,4012.0
181,2022-10-22 20:33:43,4,Home Supplies,29.746674,12.175578,71.840819,18.598521,Cloudy,4149.0
170,2023-07-10 05:51:08,5,Home Supplies,31.977397,6.173678,88.293879,22.716160,Rainy,846.0
6,2023-01-31 19:08:15,3,Beverages,21.155694,19.328947,58.008413,20.555556,Cloudy,1297.0
205,2023-09-16 21:35:36,2,Beverages,20.240589,5.954934,68.110435,9.192811,Rainy,1305.0
119,2022-06-19 23:49:31,4,Electronics,26.645494,3.014041,48.027952,18.441823,Cloudy,4954.0
193,2022-03-02 01:41:10,2,Home Supplies,30.729847,15.065555,44.485898,7.885065,Cloudy,3496.0
200,2023-11-08 01:35:40,1,Snacks,31.668767,1.627306,54.243730,8.144431,Rainy,410.0
169,2022-07-17 07:27:57,2,Electronics,30.277772,8.621069,77.160038,7.983601,Sunny,929.0
265,2023-07-06 12:24:13,2,Snacks,24.679453,1.116369,63.039660,7.252291,Cloudy,4526.0
222,2022-02-16 06:12:05,5,Beverages,34.620837,5.181076,82.814639,19.039400,Cloudy,634.0
224,2022-12-08 22:26:54,4,Clothing,31.520578,8.430352,60.435158,15.068271,Rainy,3382.0
192,2022-01-05 23:58:31,1,Beverages,19.638777,1.157478,63.832710,12.871991,Rainy,2782.0

In [ ]:
final_df = df5[['Date', 'Store_ID','Product_Category','Predicted_Sales']]
final_df

                    Date  Store_ID Product_Category  Predicted_Sales
0    2022-06-22 20:49:43         3        Beverages           4277.0
1    2022-01-08 23:00:39         2         Clothing           1353.0
2    2023-04-18 10:32:28         2      Electronics            759.0
3    2023-12-15 23:47:44         4      Electronics           4912.0
4    2022-06-12 19:11:12         2           Snacks           4430.0
..                   ...       ...              ...              ...
295  2022-09-04 16:26:17         4         Clothing           1586.0
296  2023-04-24 10:50:53         2         Clothing            946.0
297  2023-12-23 09:32:05         2           Snacks            205.0
298  2022-03-03 22:18:55         2           Snacks           4417.0
299  2023-05-12 05:56:33         1           Snacks           4702.0

[300 rows x 4 columns]

In [ ]:
final_df.to_csv("final_csv.csv")

In [ ]:
df3 = pd.read_csv('sample_submission.csv')
df3

                    Date  Store_ID Product_Category  Predicted_Sales
0    2022-06-22 20:49:43         3        Beverages             2759
1    2022-01-08 23:00:39         2         Clothing              595
2    2023-04-18 10:32:28         2      Electronics             1876
3    2023-12-15 23:47:44         4      Electronics             4805
4    2022-06-12 19:11:12         2           Snacks             4753
..                   ...       ...              ...              ...
295  2022-09-04 16:26:17         4         Clothing             4314
296  2023-04-24 10:50:53         2         Clothing             2510
297  2023-12-23 09:32:05         2           Snacks             2177
298  2022-03-03 22:18:55         2           Snacks             4719
299  2023-05-12 05:56:33         1           Snacks             1924

[300 rows x 4 columns]